156 rework scheduleclasstask UI buttons to be inline with app UI 050424
acmauth/StudentCompanion pull request #194
Opened 2024-05-29 17:46 UTC by balaktsisc

Core re-implementation of calendar

2024-05-29 18:39 UTC, neron-png commented
Όταν ο χρήστης συμπληρώνει κάτι λάθος ή το αφήνει κενό, γίνεται να βγάζει ένδειξη και στο πεδίο που έχει το θέμα;
![image](https://github.com/acmauth/StudentCompanion/assets/18248043/fb138e06-8934-4ea1-ad34-841ebda47cf3)

2024-05-29 18:41 UTC, neron-png commented
Στο picker κόβεται η σκιά, κι επίσης είναι πολύ έντονη σε σχέση με αυτές που έχουμε στην εφαρμογή.
Μια πρόταση θα ήταν να μπει box-shadow: var(--shadow-sm) και επίσης το container να έχει overflow:visible ή να μεγαλώσει το ύψος του σε ξέρω γω 5 rem

![image](https://github.com/acmauth/StudentCompanion/assets/18248043/3b834ec4-15fa-49b6-8fd8-bf7b8b7328b3)

2024-05-29 18:43 UTC, neron-png commented
Όταν μπει ένα event και πατήσει ο χρήστης να βάλει νέο, ο Τίτλος κρατάει η τιμή του παλαιού προ-συμπληρωμένο

2024-05-29 18:55 UTC, neron-png commented
These are aligned at the top, not at the center so it looks a bit goofy
![image](https://github.com/acmauth/StudentCompanion/assets/18248043/0ae3e8e8-8ae0-4a83-94f6-87e06d726836)

2024-05-29 19:10 UTC, neron-png commented
Εκεί που κάνεις import stylesheet, έχεις ένα selector για component, αυτό προτείνω να αλλάξει για κλάση, αλλιώς θα αλλάξει και σε άλλα μέρη της εφαρμογής

![image](https://github.com/acmauth/StudentCompanion/assets/18248043/8348801c-a723-4168-9d9f-5452dee09aef)

2024-05-29 19:28 UTC, neron-png commented
Add href="" to the ion cards in the events, so it displays a hold effect when the user taps them
![image](https://github.com/acmauth/StudentCompanion/assets/18248043/47c46e04-7192-4ba8-bc6d-d41d790e07a8)

2024-06-21 08:27 UTC, neron-png requested changes
Added feedback

2024-06-21 12:28 UTC, balaktsisc reviewed
Okay

2024-06-22 12:20 UTC, neron-png approved these changes
LGTM

2024-06-22 12:38 UTC, merged