Dark mode
acmauth/StudentCompanion pull request #196
Opened 2024-06-13 14:15 UTC by Kostaga

added toggle button functionality (finally), check theme when user enters app, change system bar on theme change. Problem with system navbar not changing immediately. Possible solution: https://github.com/hugotomazi/navigation-bar

2024-06-17 10:33 UTC, balaktsisc approved these changes

2024-06-17 20:26 UTC, neron-png commented
I'll approve once I run it

2024-06-20 15:39 UTC, neron-png commented
Μια διόρθωση στο search bar, να φύγει το white outline
![image](https://github.com/acmauth/StudentCompanion/assets/18248043/78cadb0f-54fd-4753-b758-84113b170374)

2024-06-20 15:42 UTC, neron-png commented
Να φιξάρουμε λίγο το εικονίδιο για τα email
![image](https://github.com/acmauth/StudentCompanion/assets/18248043/e5157da4-ab14-4861-bfe3-1023b2e3da15)

2024-06-20 21:39 UTC, neron-png commented
Αν γίνεται να αλλάξει το navigation bar του Android για να έχει το ίδιο χρώμα με το navbar μας. 

Επίσης τα header όταν είναι collapsed να παραμένουν σκούρα ίσως (?) τώρα πάει σε ένα γκρι και φαίνεται λίγο περίεργο. Δεν ξέρω στην πράξη, θέλει δοκιμή 

- [ ] Done navbar
- [ ] Done header

![Screenshot_20240621_003722_Aristomate.jpg](https://github.com/acmauth/StudentCompanion/assets/18248043/613ae934-9939-4f2e-8971-dd2a7da52e2a)

2024-06-20 21:55 UTC, neron-png commented
Αν γίνεται να αλλάξει το navigation bar του Android για να έχει το ίδιο χρώμα με το navbar μας. 

Επίσης τα header όταν είναι collapsed να παραμένουν σκούρα ίσως (?) τώρα πάει σε ένα γκρι και φαίνεται λίγο περίεργο. Δεν ξέρω στην πράξη, θέλει δοκιμή 

- [ ] Done navbar
- [ ] Done header

![Screenshot_20240621_003722_Aristomate.jpg](https://github.com/acmauth/StudentCompanion/assets/18248043/613ae934-9939-4f2e-8971-dd2a7da52e2a)

  
Επίσης το splash screen να αλλάξουμε σε dark

- [ ] Done

2024-06-21 08:28 UTC, neron-png requested changes
Added feedback

2024-06-23 20:34 UTC, Kostaga commented
> Added feedback
Έγιναν οι αλλαγές εκτος του header. Δεν μπορεσα να το αλλαξω χρωμα λιγο που το εψαξα. Αν θες το βλεπουμε και μαζι.

2024-06-27 08:46 UTC, neron-png approved these changes

2024-06-27 08:46 UTC, merged