Guide revisited
acmauth/StudentCompanion pull request #222
Opened 2024-08-12 17:13 UTC by TolisSth

2024-08-12 19:01 UTC, balaktsisc requested changes, later dismissed
Μια χαρά γενικά. Μερικά σχόλια:
- [x] Το homepage έχει χαθεί (κατά το rebase dev λογικά).
- [x] Η τελευταία σελίδα έχει λάθος εικόνα (έχει την ίδια με το ημερολόγιο).
- [ ] ~~Πρέπει να ρυθμιστεί το **πότε** θα εμφανιστεί (κάπως να προσδιοριστεί το _πρώτο_ άνοιγμα).~~ _Νέρων_: Ανοίγει μετά το login, οπότε κομπλέ. Ίσως να μπει ένα κουμπί στα settings για αμα θελήσει ο χρήστης να το δει ξανά άλλη στιγμή.
- [x] Προαιρετικά, θα ήταν ωραίο αν πέρα από το κουμπί "Επόμενο" να μπορούσε να κάνει και swipe (ως εναλλακτική) ο χρήστης για μπρος-πίσω κινήσεις.

2024-08-16 22:06 UTC, neron-png requested changes
- [x] Δεν δουλεύει σωστά στο Dark theme, Θέλει να αλλάζει ο τίτλος σε κάποιο light χρώμα
<img src="https://github.com/user-attachments/assets/41ba49ff-1180-4135-906a-9ad3e36b535d" height="200" />

- [x] Κάτι περίεργο παίζει με αυτό το κουμπί, τι έχεις κάνει;
![image](https://github.com/user-attachments/assets/cbae594f-d786-40d8-b1f3-b0b75a5e7538)

- [x] Δεν είναι responsive, κόβεται κάτω
![image](https://github.com/user-attachments/assets/a0692948-aef6-4f6e-9b50-8924d307c3bf)

- [x] Καλύτερα βγάλε το από το pages directory, αφού είναι fullscreen εξάλλου, ποιό το νόημα να είναι modal και να έχει το navbar, χώρια που χαλάει σε άλλα aspect ratio

![image](https://github.com/user-attachments/assets/a83dba26-c66b-402a-b3a4-2990542d0f10)

- [ ] Θέλει Swiper

- [x] Το "Κομπλέ τα ξέρω" δεν σε πάει στο homepage

2024-08-19 16:27 UTC, TolisSth commented
> Μια χαρά γενικά. Μερικά σχόλια:
> 
>     * [ ]  Το homepage έχει χαθεί (κατά το rebase dev λογικά).
> 
>     * [ ]  Η τελευταία σελίδα έχει λάθος εικόνα (έχει την ίδια με το ημερολόγιο).
> 
>     * [ ]  ~Πρέπει να ρυθμιστεί το **πότε** θα εμφανιστεί (κάπως να προσδιοριστεί το _πρώτο_ άνοιγμα).~ _Νέρων_: Ανοίγει μετά το login, οπότε κομπλέ. Ίσως να μπει ένα κουμπί στα settings για αμα θελήσει ο χρήστης να το δει ξανά άλλη στιγμή.
> 
>     * [ ]  Προαιρετικά, θα ήταν ωραίο αν πέρα από το κουμπί "Επόμενο" να μπορούσε να κάνει και swipe (ως εναλλακτική) ο χρήστης για μπρος-πίσω κινήσεις.

Ευχαριστώ. Κάποιες διευκρινήσεις χρειάζομαι: 
- Τι εννοούμε ότι το homepage έχει χαθεί, τα κουμπιά δεν οδηγούν εκεί; 
- Το τεστ έγινε και σε android και σε web για αυτά τα 2 (προσπαθώ να κατανοήσω που υπήρξε το routing issue καθώς ο κώδικας κάνει redirect στο homepage) 

Κατά τα άλλα δεκτό, άμα συμφωνείτε θα προσθέσω μια ρύθμιση για τον οδηγό και δεύτερον θα κοιτάξω να διορθώσω τις απροσεξίες.

2024-08-19 16:29 UTC, TolisSth commented
> * [ ]  Δεν δουλεύει σωστά στο Dark theme, Θέλει να αλλάζει ο τίτλος σε κάποιο light χρώμα
> 
> 
> <img alt="" height="200" src="https://private-user-images.githubusercontent.com/18248043/358738246-41ba49ff-1180-4135-906a-9ad3e36b535d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwODQ2ODgsIm5iZiI6MTcyNDA4NDM4OCwicGF0aCI6Ii8xODI0ODA0My8zNTg3MzgyNDYtNDFiYTQ5ZmYtMTE4MC00MTM1LTkwNmEtOWFkM2UzNmI1MzVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE2MTk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1N2I4NDRjZjEwOTQ3YjkxNzFmNDQ3NmQxMGFjYmMwNjMyNzE0Mzg5OWFkZjVlNTkyZjlmN2QzYTM1NjZkODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1VvZTNR_Cy0xZeSgpfq_TOcQDNcV9b5E025BV1ioIB0">
> 
>     * [ ]  Κάτι περίεργο παίζει με αυτό το κουμπί, τι έχεις κάνει;
>       ![image](https://private-user-images.githubusercontent.com/18248043/358738661-cbae594f-d786-40d8-b1f3-b0b75a5e7538.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwODQ2ODgsIm5iZiI6MTcyNDA4NDM4OCwicGF0aCI6Ii8xODI0ODA0My8zNTg3Mzg2NjEtY2JhZTU5NGYtZDc4Ni00MGQ4LWIxZjMtYjBiNzVhNWU3NTM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE2MTk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMmIyZTQ5ZjI3Yzk2OTQzODM4ZTA0MDE4ZjE1YTU0YTIwOGNlMzhkMTRkNmVjNDk1MTQ1ZDE0OTM1ODg3NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ocp5u9z81L-c7ObPnQXU5shwMjIrJgMc05xIFrTUkKw)
> 
>     * [ ]  Δεν είναι responsive, κόβεται κάτω
>       ![image](https://private-user-images.githubusercontent.com/18248043/358738838-a0692948-aef6-4f6e-9b50-8924d307c3bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwODQ2ODgsIm5iZiI6MTcyNDA4NDM4OCwicGF0aCI6Ii8xODI0ODA0My8zNTg3Mzg4MzgtYTA2OTI5NDgtYWVmNi00ZjZlLTliNTAtODkyNGQzMDdjM2JmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE2MTk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkYTA1NGQyNDVkNTIzMTE2ZjI5NDFmY2RmMWQzMjhiMDA1Y2QxNjU2ZmFlZjFlNTFkZmNkYjI0ZWYyNjJjMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pyUOnWLV-E5bNjYC_dc8d0Psfnz6w2A6fHLnPQFqca0)
> 
>     * [ ]  Καλύτερα βγάλε το από το pages directory, αφού είναι fullscreen εξάλλου, ποιό το νόημα να είναι modal και να έχει το navbar, χώρια που χαλάει σε άλλα aspect ratio
> 
> 
> ![image](https://private-user-images.githubusercontent.com/18248043/358739365-a83dba26-c66b-402a-b3a4-2990542d0f10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwODQ2ODgsIm5iZiI6MTcyNDA4NDM4OCwicGF0aCI6Ii8xODI0ODA0My8zNTg3MzkzNjUtYTgzZGJhMjYtYzY2Yi00MDJhLWIzYTQtMjk5MDU0MmQwZjEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE2MTk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxZTFiYjNkYjBlOWUxMDIwMzdlMjM2MWI2ZTgzNTFjYTcxOGZlOWNmOGNhODY0ZTMzNGFhOGU5MmUzOTVhMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YEsR53IJf3hlF7TrlWj6uzuQo1_VRCDDGitYj5NC1Cc)
> 
>     * [ ]  Θέλει Swiper
> 
>     * [ ]  Το "Κομπλέ τα ξέρω" δεν σε πάει στο homepage

Κάποιες διευκρινήσεις θα ζητήσω: 
- Τι χρώμα θα χρειαστούμε για τον τίτλο 
- Σε τι πλατφόρμα τέσταρες 
- Είχες dark mode όλη την ώρα ανοικτό; 

Επίσης το κουμπί φαίνεται περίεργα λόγω dark theme. Κατά τα θέματα του routing δεν μπορώ να κατανοήσω γιατί δεν πηγαίνει στο homepage.

2024-08-20 11:54 UTC, balaktsisc commented
> Ευχαριστώ. Κάποιες διευκρινήσεις χρειάζομαι:
> 
> * Τι εννοούμε ότι το homepage έχει χαθεί, τα κουμπιά δεν οδηγούν εκεί;
> * Το τεστ έγινε και σε android και σε web για αυτά τα 2 (προσπαθώ να κατανοήσω που υπήρξε το routing issue καθώς ο κώδικας κάνει redirect στο homepage)
> 
> Κατά τα άλλα δεκτό, άμα συμφωνείτε θα προσθέσω μια ρύθμιση για τον οδηγό και δεύτερον θα κοιτάξω να διορθώσω τις απροσεξίες.

Μάλλον υπήρχε confilct με τις εκδόσεις των πακέτων κατά το rebasing. Φαινομενικά όντως ο κωδικά σου μοιάζει λειτουργικός, οπότε αν σου τρέχει, ΟΚ

2024-08-20 12:45 UTC, neron-png commented
> * Τι χρώμα θα χρειαστούμε για τον τίτλο
Ας το κάνουμε λευκό
 
> * Σε τι πλατφόρμα τέσταρες
> * Είχες dark mode όλη την ώρα ανοικτό;
Chrome (mobile από devtools) και ναι

> Επίσης το κουμπί φαίνεται περίεργα λόγω dark theme. Κατά τα θέματα του routing δεν μπορώ να κατανοήσω γιατί δεν πηγαίνει στο homepage.
Δεν φαίνεται περίεργο λόγω dark mode, και στο light theme έτσι είναι. Όταν το πατάω πάλι κάνει highlight τη λάθος περιοχή
![image](https://github.com/user-attachments/assets/8830d194-ad10-478e-b681-7e0d536675d2)

Επίσης σχετικά με το κουμπί. Γιατί πήγες μέσω Κίνας και έβαλες τσιπ, μόνο για να το εξαφανίσεις με css και μετά να ξαναγράψεις css για ένα chip μέσα του. Δεν βγάζει νόημα. Δες πόσο απλό θα μπορούσε να είναι και φτιάχνεται και το πρόβλημα που είχαμε και είναι και σωστό.
![image](https://github.com/user-attachments/assets/389816ca-5597-44a8-a1b0-cb9f93e25837)

Όμοια και στο guide μέσα θα πρότεινα λίγο καθάρισμα και να εφαρμόσεις και τα άλλα που είπα στο αρχικό σχόλιο, αλλά μέχρι τότε ορίστε ένα κόλπο για να αλλάξεις το χρώμα μεταξύ light και dark
![image](https://github.com/user-attachments/assets/747fb824-1b8f-4a04-8b19-401895fad0f2)

2024-09-07 09:11 UTC, neron-png approved these changes

2024-09-07 09:16 UTC, merged